#This is the workflow name
name: Hello workflow 
#runs on a trigger 
on:
  push:
    branches: [main]

#These are jobs inside the workflow
jobs:

#this is the name of the job
   greet:
#this is GitHub runner, each job runs on a runner
     runs_on: ubuntu-latest
     step:
       - name: say hello to users
         run: echo "Hello dosto."
         
