# This is the workflow name
name: Hello workflow

on:
  # Manual trigger with inputs
  workflow_dispatch: 
    inputs:
      environments:
        description: 'THIS IS THE ENVIRONMENT VALUE WHERE THE WORKFLOW RUNS'
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

  # Automatic trigger when HTML files change on the main branch
  push:
    branches:
      - main
    paths:
      - '**.html'

# These are jobs inside the workflow
jobs:
  # This is the name of the job
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code clone from GitHub."

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Docker Container
        run: echo "Docker Container Created."

  Test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Testing the container."

  deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: echo "deployment succeeded."
