name: Deploy Flask app

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: deploy with dockercompose
              uses: 